# Generated by Django 5.0.6 on 2024-09-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='menus', to='apps.menucategory'),
        ),
    ]
