# Generated by Django 5.0.6 on 2024-09-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_menu_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categories',
        ),
    ]
